### ISSUE TITLE
"Calling delete on expression not allowed in strict mode"

### ISSUE THREAD

**Issue by mattlockyer** [inf3rno/u3#3]
When bundling with Parcel 2 RC 1

![image](https://user-images.githubusercontent.com/321340/134177715-f7073c0d-ca42-4216-a7ef-af7c149a5113.png)

Reason:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Delete_in_strict_mode

Fix for `cache.js`:

```
var cache = function (fn) {
    var called = false,
        store;

    if (!(fn instanceof Function)) {
        called = true;
        store = fn;
        fn = null;
    }

    return function () {
        if (!called) {
            called = true;
            store = fn.apply(this, arguments);
			fn = null;
        }
        return store;
    };
};

module.exports = cache;
```

**Comment by inf3rno** [comment]
@mattlockyer 
I'll fix this tomorrow, thanks for reporting!

**Comment by inf3rno** [comment]
Okay, I would not call this bug, because strict mode support was never planned in my libs. I opened a new feature thread for it. #4 You can track it there, I close this.
